export const characterVariables = {
    names: ["Aethelred", "Brynja", "Cedric", "Dariana", "Edric", "Faeira", "Garen", "Hadrian", "Iliana", "Jarek", "Kaelen", "Lirien", "Magnus", "Niamh", "Oren", "Petra", "Quinlan", "Riven", "Sariel", "Thalia", "Ulrich", "Vespera", "Wren", "Xander", "Ysabel", "Zephyr"],
    classes: ["Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard"],
    races: ["Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", "Half-Orc", "Halfling", "Human", "Tiefling", "Goliath"],
    objectives: [
        "To find and reclaim a lost family heirloom",
        "To avenge a loved one's death",
        "To gain riches and become wealthy",
        "To prove oneself to a rival",
        "To escape a life of poverty and hardship",
        "To explore the world and discover its secrets",
        "To find a cure for a deadly illness",
        "To gain power and influence in the world",
        "To restore a fallen kingdom or civilization",
        "To seek out rare and powerful magical artifacts",
        "To fulfill a prophecy or divine mission",
        "To prove oneself to a deity or religious order",
        "To uncover a conspiracy or uncover a plot against a kingdom",
        "To rescue a kidnapped loved one or friend",
        "To prove one's innocence of a crime",
        "To explore and conquer a dangerous wilderness",
        "To gain fame and recognition as a hero",
        "To gain revenge against a former friend who betrayed them",
        "To protect the innocent from a powerful threat",
        "To gain knowledge of a forbidden lore",
        "To find and oppressed individuals",
        "To liberate a conquered nation",
        "To establish a new settlement in uncharted lands",
        "To find a legendary lost civilization",
        "To find and study rare creatures",
        "To gain mastery over a specific form of magic",
        "To learn the truth behind a mysterious occurrence",
        "To prove oneself as a worthy member of his guild",
        "To restore a sacred site that has been desecrated",
        "To find and communicate with powerful extraplanar entities",
        "To find and study ancient technologies",
        "To become the greatest explorer of all time",
        "To protect a loved one from harm",
        "To learn the truth about their past",
        "To find and redeem a former enemy",
        "To prevent a catastrophic magical event",
        "To prevent a war between nations",
        "To uncover the source of a dangerous plague",
        "To establish a trade route in uncharted lands",
        "To gain vengeance against a powerful foe who has wronged them",
        "To find and explore an ancient tomb",
        "To establish a new order dedicated to a specific belief",
        "To find and destroy a powerful artifact that threatens the world",
        "To establish a new form of government in a specific region",
        "To rescue and protect a magical creature from extinction",
        "To become a legendary performer",
        "To be a renowned scholar",
        "To gain mastery over a specific form of elemental magic",
        "To establish a new trade route or network between nations",
        "To find and explore a dangerous and mysterious jungle",
        "To prevent the rise of a powerful and evil wizard",
        "To gain knowledge of a rare and powerful form of necromancy",
        "To find and reclaim a lost religious artifact",
        "To become a master of a specific form of combat style",
        "To protect a community from harm",
        "To be renowned diplomat",
        "To find and study rare and powerful forms of alchemy",
        "To create a powerful new spell",
        "To create a powerful new magical item",
        "To establish a new form of art",
        "To prevent the destruction of a monument",
        "To gain knowledge of a specific form of divine magic",
        "To find and explore a dangerous and mysterious desert",
        "To prevent the rise of a powerful demon",
        "To gain knowledge of a specific form of magical creature",
        "To create a new form of technology",
        "To protect an individual from assassination",
        "To kill a king",
        "To find a lost library",
        "To be a renowned craftsman",
        "To prevent the rise of a powerful dragon",
        "To prevent the rise of a powerful lich",
        "To become a respected member of the local guild",
        "To marry into a wealthy and powerful family",
        "To become a skilled blacksmith and create legendary weapons",
        "To find a rare and powerful magical artifact",
        "To become a trusted advisor to the local lord",
        "To lead a successful rebellion against an oppressive ruler",
        "To join a group of adventurers and explore the world",
        "To become a powerful mage and master of the arcane arts",
        "To train and raise a champion warhorse",
        "To discover the truth behind a family curse",
        "To become a renowned healer and cure diseases",
        "To become a skilled hunter and track down dangerous beasts",
        "To find a lost civilization and uncover its secrets",
        "To lead a group of mercenaries and win a decisive battle",
        "To become a legendary bard and compose epic songs",
        "To become a skilled diplomat and negotiate treaties",
        "To build a grand castle and establish a noble house",
        "To become a master thief and steal valuable treasures",
        "To become a wise sage and impart knowledge to future generations",
        "To become a powerful cleric and serve a god",
        "To start a successful trading business and become wealthy",
        "To find a lost love and rekindle a long lost romance",
        "To become a feared pirate and rule the seas",
        "To become a skilled navigator and explore uncharted waters",
        "To become a legendary warrior and lead armies to victory",
        "To become a skilled alchemist and create powerful potions",
        "To become a renowned artist and create beautiful works of art",
        "To become a successful merchant and trade goods across the land",
        "To become a powerful necromancer and command the undead",
        "To become a wise scholar and study ancient texts",
        "To become a skilled sailor and navigate dangerous waters",
        "To become a renowned chef and cook delicious meals",
        "To become a master falconer and train birds of prey",
        "To become a successful farmer and feed the local populace",
        "To become a skilled woodworker and craft beautiful furniture",
        "To become a successful innkeeper and provide a comfortable stay for travelers",
        "To become a powerful ranger and protect the wilderness",
        "To become a skilled brewer and create delicious ale",
        "To become a successful horse breeder and raise magnificent steeds",
        "To become a skilled weaver and create beautiful tapestries",
        "To become a powerful dragon slayer and rid the land of dangerous beasts",
        "To become a skilled apothecary and create healing remedies",
        "To become a successful miner and extract valuable ores",
        "To become a skilled falconer and train hunting birds",
        "To become a successful lumberjack and provide wood for building",
        "To become a renowned storyteller and entertain the masses",
        "To become a skilled leatherworker and create durable armor",
        "To become a successful fisherman and provide food for the local populace",
        "To become a skilled siege engineer and design powerful weapons",
        "To become a successful beekeeper and harvest delicious honey",
        "To Protect the kingdom from invading armies",
        "To Avenge the death of a loved one",
        "To Recover a stolen artifact of great importance",
        "To Ascend to the throne and become ruler of the kingdom",
        "To Uncover a conspiracy against the kingdom's rulers",
        "To Discover the truth about a mysterious prophecy",
        "To Train to become a powerful mage or wizard",
        "To Retrieve a powerful magical artifact from a dangerous dungeon",
        "To Find a cure for a deadly plague spreading across the kingdom",
        "To Lead a rebellion against an oppressive ruler",
        "To Rescue a kidnapped prince or princess",
        "To Protect a caravan traveling through dangerous territory",
        "To Hunt down a notorious bandit leader",
        "To Explore an ancient ruin to uncover lost knowledge or treasures",
        "To Win a tournament of champions to prove their worth",
        "To Defend a small village from raiders or monsters",
        "To Seek revenge against a powerful enemy",
        "To Travel to a distant land to learn about new cultures and gain knowledge",
        "To Become a renowned bard or musician and entertain audiences across the kingdom",
        "To Solve a mystery surrounding a haunted castle",
        "To Defeat a powerful dragon terrorizing the countryside",
        "To Find a lost artifact that could turn the tide of a war",
        "To Assist a group of rebels in overthrowing an oppressive government",
        "To Become a legendary warrior and inspire others with their deeds",
        "To Train to become a skilled assassin or spy",
        "To Rescue a damsel in distress from a wicked sorcerer",
        "To Gather a group of adventurers to complete a dangerous quest",
        "To Establish a guild of adventurers to help others in need",
        "To Track down a traitor who has betrayed the kingdom",
        "To Learn to control powerful magical abilities and use them for good",
        "To Become a trusted advisor to the king or queen",
        "To Develop a powerful new weapon to defeat enemies",
        "To Become a renowned blacksmith or craftsman and create legendary weapons",
        "To Build a network of informants to gather information on enemies",
        "To Establish a network of safe houses for refugees fleeing war or persecution",
        "To Protect a sacred temple from desecration",
        "To Discover the truth about a mysterious cult",
        "To Help a group of nomads find a new home",
        "To Defend a trade route from bandits or pirates",
        "To Become a master hunter and track down dangerous beasts",
        "To Build a fortress to protect a vulnerable border",
        "To Infiltrate an enemy stronghold to gather intelligence",
        "To Train to become a skilled archer or marksman",
        "To Learn to control powerful magical creatures to aid in battle",
        "To Become a renowned healer and cure the sick and wounded",
        "To Seek out ancient knowledge to help defeat a powerful enemy",
        "To Protect a group of travelers on a dangerous journey",
        "To Establish a new settlement in a dangerous wilderness",
        "To Protect a powerful artifact from falling into the wrong hands",
        "To Develop a new form of magic that could change the world",
    ],
    personalityQuirks: [
        "Talks to animals as if they can understand",
        "Always carries a lucky rabbit's foot",
        "Refuses to wear shoes",
        "Constantly humming or singing to themselves",
        "Has an irrational fear of the dark",
        "Collects strange or rare books",
        "Speaks in riddles or rhymes",
        "Cannot resist the temptation of treasure",
        "Believes they have a special connection to the gods",
        "Is convinced that they are cursed",
        "Is obsessed with cleanliness and hygiene",
        "Always wears a certain amulet for protection",
        "Has a habit of counting everything",
        "Talks to themselves when they think no one is listening",
        "Believes in astrology and always checks their horoscope",
        "Has an insatiable sweet tooth",
        "Refuses to eat anything that's not cooked over an open fire",
        "Talks to inanimate objects as if they were alive",
        "Is always scribbling in a journal or sketchbook",
        "Has a secret talent for playing the lute or other musical instrument",
        "Cannot resist a good challenge or bet",
        "Is convinced that they have a secret destiny",
        "Has a fascination with dragons or other mythical creatures",
        "Is always searching for hidden meanings in everything",
        "Refuses to sleep in a bed, preferring to sleep on the ground",
        "Has a habit of telling tall tales or exaggerating the truth",
        "Is prone to sudden mood swings",
        "Is afraid of loud noises",
        "Has a love for puzzles and riddles",
        "Cannot stand the sight of blood",
        "Is always trying out new and unusual foods",
        "Has a secret love for poetry",
        "Has an uncanny ability to find their way in any situation",
        "Is always inventing new gadgets or contraptions",
        "Refuses to wear armor in battle, believing it hinders their movements",
        "Has a tendency to talk too much",
        "Is convinced that they are being followed by a shadowy figure",
        "Is fascinated by ancient ruins and relics",
        "Has a fear of heights",
        "Is always trying to improve their swordsmanship or archery skills",
        "Believes in ghosts and spirits",
        "Cannot resist the urge to explore new places",
        "Has a deep love of nature and the outdoors",
        "Is convinced that they can communicate with the dead",
        "Is always looking for ways to improve their health and wellbeing",
        "Has a secret passion for dance",
        "Is fascinated by the art of war and strategy",
        "Has a fear of enclosed spaces",
        "Cannot resist a good prank",
        "Is convinced that they are being watched by invisible eyes",
        "Is always doodling or drawing in the margins of their books",
        "Has a fascination with alchemy and the occult",
        "Is always trying to solve puzzles and riddles",
        "Refuses to eat meat, believing it to be immoral",
        "Is convinced that they have a guardian angel",
        "Has an obsession with collecting rare coins or artifacts",
        "Is always trying to learn a new language",
        "Has a fear of spiders or insects",
        "Cannot resist the lure of a good adventure",
        "Is always trying to find the perfect balance between work and play",
        "Has a secret talent for storytelling",
        "Is convinced that they can talk to trees",
        "Has a fascination with astronomy and the stars",
        "Is always trying to find ways to improve their physical strength",
        "Cannot resist the temptation of a good mystery",
        "Is convinced that they have a magical power",
        "Has a fear of water",
        "Has a fascination with ancient myths and legends",
        "Is always trying to find ways to help others",
        "Is convinced that they have a sixth sense",
        "Has a love for collecting rare herbs and spices",
        "Is always trying to find the perfect hiding spot",
        "Has a tendency to talk in third person",
        "Is fascinated by the art of potion-making",
        "Refuses to eat food that's not blessed by a priest",
        "Is convinced that they have a guardian spirit",
        "Has a love for collecting rare weapons",
        "Is always trying to find ways to improve their intelligence and knowledge",
        "Has a fear of fire",
        "Cannot resist the urge to explore abandoned places",
        "Is always trying to find the perfect angle for their shots, as they are a budding archer",
        "Has a secret talent for painting or drawing",
        "Is convinced that they are immune to any poison",
        "Has a fascination with ancient scripts and languages",
        "Is always trying to find ways to improve their speed and agility",
        "Cannot resist the lure of a good challenge, like a duel or joust",
        "Is convinced that they are a reincarnation of a famous hero or warrior",
        "Has a love for collecting rare gems and minerals",
        "Is always trying to find the perfect way to blend into their surroundings",
        "Has a tendency to talk to themselves in different accents",
        "Is fascinated by the art of archery and always trying to improve their aim",
        "Refuses to wear any clothing that's not handmade",
        "Is convinced that they have a natural talent for magic",
        "Has a love for collecting rare historical artifacts",
        "Is always trying to find ways to improve their reflexes",
        "Has a fear of thunderstorms",
        "Cannot resist the lure of a good mystery, like a cursed treasure or an unsolved murder",
        "Is convinced that they are a master of disguise",
        "Has a fascination with ancient weapons and armors",
        "Has a tendency to set things on fire",
        "Is Afraid of the dark",
        "Has Fear of heights",
        "Has Claustrophobia",
        "Has Fear of fire",
        "Has Fear of water",
        "Has Fear of spiders",
        "Has Fear of snakes",
        "Has Fear of rats",
        "Has Fear of bats",
        "Has Fear of thunderstorms",
        "Has Fear of lightning",
        "Has Fear of ghosts",
        "Has Fear of demons",
        "Has Fear of possession",
        "Has Fear of magic",
        "Has Fear of being buried alive",
        "Has Fear of disease",
        "Has Fear of death",
        "Has Fear of being alone",
        "Has Fear of crowds",
        "Has Fear of betrayal",
        "Has Fear of failure",
        "Has Fear of being caught",
        "Has Fear of being punished",
        "Has Fear of being forgotten",
        "Has Fear of the unknown",
        "Fears change",
        "Has Fear of losing control",
        "Fears being powerless",
        "Fears the dark arts",
        "Talks too loudly",
        "Always interrupts others",
        "Constantly fidgets with their clothing or accessories",
        "Always wants to be the center of attention",
        "Has an unusual laugh",
        "Speaks in a singsong or rhythmic manner",
        "Talks with their hands excessively",
        "Always has a witty retort or comeback",
        "Frequently interrupts others to correct them",
        "Uses excessive flattery or compliments",
        "Talks to themselves or mumbles under their breath",
        "Has a habit of repeating other people's words or phrases",
        "Talks in a whisper or very quiet voice",
        "Uses a lot of hand gestures and facial expressions",
        "Always puts others first",
        "Has a tendency to give unsolicited advice",
        "Cannot stand to see others in pain",
        "Has a habit of over-explaining things to others",
        "Always assumes the best in people",
        "Cannot stand to see anyone mistreated",
        "Has a habit of hugging or touching others frequently",
        "Is overly critical of others' behavior",
        "Always tries to cheer others up when they're down",
        "Has a tendency to speak for others",
        "Is very protective of those they care about",
        "Has a habit of baking or cooking for others",
        "Is overly sentimental or emotional",
        "Has a tendency to mother or smother others",
        "Always tries to make others feel included",
        "Is very perceptive about others' feelings",
        "Is overly competitive with others",
        "Has a tendency to gossip or spread rumors about others",
        "Always tries to bring out the best in others",
        "Is very forgiving of others' mistakes",
        "Has a habit of giving gifts to others for no reason",
        "Is overly sensitive to criticism",
        "Has a tendency to micromanage others",
        "Always tries to be a mediator in conflicts between others",
        "Is very patient with others, even when they are difficult",
        "Has a habit of mentoring or teaching others",
        "Is overly suspicious of others' motives",
        "Always tries to keep the peace between others",
        "Is very persuasive and can talk others into doing things",
        "Has a tendency to be too accommodating and put their own needs last",
        "Arrogant and condescending towards others",
        "Quick to judge others and hold grudges",
        "Manipulative and deceitful in their interactions with others",
        "Stubborn and unwilling to compromise",
        "Always puts their own needs before others",
        "Dismissive of others' opinions and feelings",
        "Untrustworthy and unreliable in their promises and commitments",
        "Emotionally distant and aloof towards others",
        "Uses others for their own gain without regard for their well-being",
        "Aggressively competitive with others",
        "Unapologetically selfish and greedy",
        "Isolates themselves from others and avoids social interaction",
        "Blames others for their own mistakes and shortcomings",
        "Scapegoats others to avoid taking responsibility for their actions",
        "Disrespectful and rude towards others",
        "Refuses to apologize or make amends for their mistakes",
        "Betrays the trust of others through lies and deceit",
        "Refuses to listen to the opinions or advice of others",
    ],
    physicalQuirks: [
        "With A scar running down one side of their face",
        "With A missing tooth or teeth",
        "With A limp in one leg",
        "With A missing finger or hand",
        "With A lazy eye",
        "With A large birthmark on their face",
        "With A cleft palate",
        "With A stutter",
        "With A hunchback",
        "With A large nose",
        "With A missing ear",
        "With A crooked nose",
        "With A bald head",
        "With A unibrow",
        "With A hooked nose",
        "With A large mole on their cheek",
        "With A missing eye",
        "With A clubfoot",
        "With A large scar on their chest",
        "With A pronounced overbite",
        "With A missing arm",
        "With A large scar on their back",
        "With A thick beard",
        "With A long, thin scar on their forehead",
        "With A broken nose",
        "With A harelip",
        "With A missing leg",
        "With A thin, high-pitched voice",
        "With A large birthmark on their neck",
        "With A hump on their back",
        "With A large scar on their arm",
        "With A disfigured ear",
        "With A squint",
        "With A missing hand",
        "With A scar on their neck",
        "With A permanent frown",
        "With A large, bushy mustache",
        "With A bent nose",
        "With A missing thumb",
        "With A small nose",
        "With A missing nose",
        "With A large scar on their face",
        "With A prominent chin",
        "With A missing teeth",
        "With A broken tooth",
        "With A long scar on their leg",
        "With A receding hairline",
        "With A large scar on their hand",
        "With A sunken eye",
        "With A missing toe",
        "With A crooked smile",
        "With A missing eyebrow",
        "With A lisp",
        "With A birthmark on their forehead",
        "With A large scar on their leg",
        "With A bald spot",
        "With A large nose with a bump",
        "With A permanent scowl",
        "With A thin beard",
        "With A small scar on their cheek",
        "With A prominent brow",
        "With A missing finger",
        "With A deep voice",
        "With A large mole on their forehead",
        "With A thin mustache",
        "With A broken jaw",
        "With A large scar on their shoulder",
        "With A missing chin",
        "With A birthmark on their arm",
        "With A large scar on their abdomen",
        "With A thick accent",
        "With A missing upper lip",
        "With A missing lower lip",
        "With A birthmark on their leg",
        "With A large scar on their hip",
        "With A missing eyelash",
        "With A large nose with a wide bridge",
        "With A missing nose tip",
        "With A limp hand",
        "With A missing part of their scalp",
        "With A crooked nose bridge",
        "With A long scar on their arm",
        "With A missing earlobe",
        "With A permanent smile",
        "With A small birthmark on their chin",
        "With A large scar on their wrist",
        "With A missing toenail",
        "With A prominent nose tip",
        "With A missing toenail",
        "With A crooked eyebrow",
        "With A small scar on their neck",
        "With A missing upper eyelid",
        "With A missing lower eyelid",
        "With A birthmark on their face",
        "With A missing eyebrow hair",
        "With A missing eyelash",
        "With A large nose with flared nostrils",
        "With A birthmark on their chest",
        "With A crooked mouth",
        "With A small scar on their forehead",
        "Who Wears a hooded cloak at all times",
        "Who Wears a hat with a wide brim",
        "Who Refuses to wear shoes at all",
        "Who Always wears a red",
        "Who Wears a veil or mask to cover their face",
        "Who Wears a cape or poncho",
        "Who Has a collection of cloaks",
        "Who Wears a horned helmet",
        "Who Wears a long flowing robe",
        "Who Wears a circlet as crown",
        "Who Smells bad",
        "Who Extremely sensitive to sunlight",
        "Who Has a heightened sense of smell",
        "Who Cannot tolerate loud noises",
        "Who Has a tendency to taste everything",
        "Who Has a sixth sense for danger",
        "Who Easily gets motion sickness",
        "Who Has synesthesia",
        "Who Has a photographic memory",
        "Who Is sensitive to certain textures",
        "Who Has perfect pitch",
        "Who Has a heightened sense of touch",
        "Who Is sensitive to spicy food",
        "Who Has a sensitive stomach",
        "Who Has a heightened sense of taste",
        "Who Easily gets vertigo",
        "Who Has a sixth sense for magic",
        "Who Has a heightened sense of hearing",
        "Who Easily gets migraines",
        "Who Is sensitive to cold temperatures",
        "Who Has a heightened sense of balance",
        "Who Has a sixth sense for the supernatural",
        "Who Is sensitive to bright lights",
        "Who Easily gets seasick",
        "Who Has a heightened sense of time",
        "Who Is sensitive to hot temperatures",
        "Who Has a heightened sense of intuition",
        "Who Has perfect color vision",
        "Who Has a heightened sense of proprioception",
        "Who Easily gets car sick",
        "Who Has a heightened sense of empathy",
        "Who Is sensitive to static electricity",
        "Who Is sensitive to vibrations",
        "Who Is sensitive to psychic energy",
        "Who Is an empath",
        "Who Is sensitive to humidity",
        "Who Is sensitive to ultraviolet light",
        "Who Has a heightened sense of danger",
        "Who chews on a straw",
    ],
    locations: [
        "A massive waterfall",
        "A hidden cave system",
        "A towering volcano",
        "A vast grassy plain",
        "A misty moor",
        "A sprawling underground city",
        "A crumbling castle",
        "A treacherous mountain pass",
        "A dense jungle",
        "A desolate wasteland",
        "A winding river",
        "A tranquil lake",
        "A glittering diamond mine",
        "A sprawling metropolis",
        "A small fishing village",
        "A windswept coastal town",
        "A fortified border town",
        "A sprawling desert oasis",
        "A sprawling underground labyrinth",
        "A secret magical academy",
        "A mystical island",
        "A treacherous bog",
        "A forgotten ruin",
        "A thriving merchant city",
        "A peaceful farming community",
        "A windswept mountain peak",
        "A labyrinthine catacomb",
        "A lost temple",
        "A dark and sinister forest",
        "A treacherous icy wasteland",
        "A prosperous trading post",
        "A dense, tangled thicket",
        "A massive stone monolith",
        "A dangerous swamp",
        "A massive underground river",
        "A massive arena",
        "A bustling port town",
        "A sprawling savannah",
        "A massive underground library",
        "A sprawling magical marketplace",
        "A towering wizard's tower",
        "A hidden magical grove",
        "A massive underground stronghold",
        "A frozen tundra",
        "A sprawling network of caves",
        "A dangerous highland pass",
        "A vast subterranean lake",
        "A mystical standing stone circle",
        "A peaceful oasis",
        "A massive temple complex",
        "A remote fishing village",
        "A treacherous sea cliff",
        "A hidden glade",
        "A dangerous haunted forest",
        "A massive underground arena",
        "A labyrinthine sewer system",
        "A sprawling desert city",
        "A tranquil forest clearing",
        "A towering wizard's spire",
        "A frozen ice cave",
        "A remote mountain village",
        "A massive underground market",
        "A treacherous mountain range",
        "A sprawling enchanted garden",
        "A remote island fortress",
        "A massive underground palace",
        "A sprawling magical academy",
        "A windswept prairie",
        "A sprawling network of catacombs",
        "A mystical ley line nexus",
        "A peaceful mountain village",
        "A hidden magical cavern",
        "A dangerous bog",
        "A massive underground city",
        "A remote desert outpost",
        "A treacherous jungle path",
        "A sprawling seaside village",
        "A peaceful riverside hamlet",
        "A dangerous enchanted swamp",
        "A massive underground fortress",
        "A treacherous highland valley",
        "A mystical dragon's lair",
        "A towering wizard's keep",
        "A frozen mountain pass",
        "A remote desert oasis",
        "A massive underground library",
        "A sprawling magical bazaar",
        "A windswept cliffside",
        "A treacherous enchanted forest",
        "A massive underground arena",
        "A labyrinthine sewer system",
        "A sprawling desert metropolis",
        "A tranquil forest glade",
        "A towering wizard's citadel",
        "A frozen ice fortress",
        "A remote mountain outpost",
        "A massive underground market",
        "A treacherous mountain trail",
        "A sprawling enchanted grove",
        "A remote island sanctuary",
        "The Ruined Citadel of the Fallen King",
        "The Enchanted Forest of the Sylphs",
        "The Cursed Swamp of the Black Witch",
        "The Floating City of the Sky Pirates",
        "The Dark Abyss of the Leviathan",
        "The Frozen Tundra of the Ice Giants",
        "The Fabled Island of the Sea Serpents",
        "The Crystal Caverns of the Dwarven Kingdom",
        "The Haunted Castle of the Vampire Countess",
        "The Mystic Oasis of the Desert Djinn",
        "The Lost City of the Ancient Titans",
        "The Enchanted Garden of the Fairy Queen",
        "The Hidden Temple of the Monkey God",
        "The Great Library of the Arcane Arts",
        "The Dark Forest of the Werewolf Pack",
        "The Valley of the Gryphons",
        "The City of the Gorgons",
        "The Island of the Lizardmen",
        "The Necropolis of the Undead Pharaohs",
        "The Shadowlands of the Dark Elves",
        "The Castle of the Red Dragon",
        "The Tower of the Archmage",
        "The Sunken City of the Merfolk",
        "The Forbidden Jungle of the Amazon Queens",
        "The Cave of the Fire Giants",
        "The City of the Minotaurs",
        "The Ruins of the Ancient Civilization",
        "The Oasis of the Nomadic Tribes",
        "The Island of the Cyclops",
        "The Labyrinth of the Minotaur King",
        "The Dark Swamp of the Bog Witch",
        "The Floating Castle of the Cloud Giants",
        "The Enchanted Lake of the Water Nymphs",
        "The City of the Goblins",
        "The Ruined Temple of the Sun God",
        "The Tower of the Necromancer",
        "The Forbidden City of the Demon Lords",
        "The Valley of the Dragon Riders",
        "The Enchanted Glacier of the Ice Dragons",
        "The Castle of the Witch Queen",
        "The Island of the Kraken",
        "The Underworld of the Dark Dwarves",
        "The Ruins of the Giant Civilization",
        "The Enchanted Meadows of the Unicorn Herds",
        "The Cursed Mountain of the Yeti",
        "The City of the Orcs",
        "The Tower of the Sorcerer",
        "The Island of the Sea Monsters",
        "The Enchanted Canyon of the Thunderbirds",
        "The City of the Kobolds",
        "The Ruined Temple of the Moon Goddess",
        "The Tower of the Enchanter",
        "The Forbidden Fortress of the Dark Samurai",
        "The Valley of the Pegasus",
        "The Enchanted Reef of the Mermaids",
        "The Cursed Island of the Ghost Pirates",
        "The Ruined City of the Ancient Pharaohs",
        "The Enchanted Garden of the Dryads",
        "The Cursed Mountain of the Fire Demons",
        "The City of the Trolls",
        "The Tower of the Warlock",
        "The Island of the Giant Crabs",
        "The Forbidden Castle of the Shadow Knights",
        "The Valley of the Hippogriffs",
        "The Enchanted Lagoon of the Selkies",
        "The Cursed Forest of the Dark Fairies",
        "The Ruined Palace of the Sorceress Queen",
        "The Enchanted Grove of the Tree Ents",
        "The Cursed Mountain of the Ice Demons",
        "The City of the Giants",
        "The Tower of the Illusionist",
        "The Island of the Giant",
        "A walled fortress city",
        "A floating city in the clouds",
        "A sprawling underground metropolis",
        "A small, isolated mountain village",
        "A hidden elven tree village",
        "A bustling trading hub",
        "A fortified castle town",
        "A seaside fishing village",
        "A remote desert town",
        "A bustling seaport city",
        "A peaceful farming village",
        "A sprawling riverfront town",
        "A remote nomadic settlement",
        "A thriving mining town",
        "A floating barge city on a river",
        "A secluded hermitage",
        "A bustling metropolis built on canals",
        "A prosperous merchant town",
        "A frozen arctic village",
        "A treehouse village built in the jungle canopy",
        "A sprawling underground dwarf city",
        "A fortified border town between two kingdoms",
        "A peaceful hobbit village in the rolling hills",
        "A small mountain outpost built into a cliffside",
        "A bustling oasis city in the middle of a desert",
        "A thriving island city built on stilts in the water",
        "A remote fishing village built into a cliffside",
        "A massive trade city with bazaars, inns, and guilds",
        "A seaside resort town for the wealthy",
        "A sprawling nomadic caravan of travelers",
        "A peaceful gnome village in the forest",
        "A remote island village accessible only by boat",
        "A bustling mining town with treacherous tunnels",
        "A floating raft town on a jungle river",
        "A peaceful dragonborn village on the plains",
        "A sprawling underground goblin city",
        "A fortified town built around a massive tree",
        "A peaceful druidic settlement deep in the forest",
        "A remote, isolated farming village",
        "A bustling metropolis with winding, narrow streets",
        "A floating iceberg city in the arctic waters",
        "A small, isolated nomadic tribe on the savanna",
        "A thriving port city built on an active volcano",
        "A seaside shanty town for pirates and smugglers",
        "A sprawling underground city of the undead",
        "A fortified city built into the side of a mountain",
        "A peaceful halfling village in the fields",
        "A floating raft town on a desert river",
        "A peaceful lizardfolk village in the swamp",
        "A remote desert town with a hidden oasis",
        "A sprawling metropolis built on the ruins of an ancient city",
        "A fortified city built around a massive fortress",
        "A peaceful centaur village on the grassy plains",
        "A small, isolated mountain town accessible only by a treacherous path",
        "A bustling seaside city built on the ruins of an ancient civilization",
        "A floating airship city in the clouds",
        "A peaceful celestial settlement on a distant planet",
        "A sprawling underground city of the molefolk",
        "A fortified city built around a massive tower",
        "A peaceful satyr village in the forest",
        "A floating city of the undead on a swampy river",
        "A small, isolated fishing village accessible only by boat",
        "A fortified city built around a massive dam",
        "A peaceful aarakocra settlement on a mountain peak",
        "A remote town on the edge of a massive waterfall",
        "The Mystic Circle",
        "The Wandering Bards",
        "The Shadow Court",
        "The Order of the Crimson Dragon",
        "The Silent Sanctuary",
        "The Silver Coven",
        "The Cursed Cathedral",
        "The Dry Ocean",
        "The Blacksmiths Guild",
        "The Bakers' Union",
        "The Brewers Association",
        "The Butchers' Guild",
        "The Carpenters' Guild",
        "The Clothiers' Alliance",
        "The Cobblers' Guild",
        "The Glassmakers' Association",
        "The Healers' Guild",
        "The Innkeepers' Society",
        "The Jewelers' Guild",
        "The Masons' Guild",
        "The Mercenaries' League",
        "The Miners' Guild",
        "The Painters' Guild",
        "The Potters' Guild",
        "The Scribes' Guild",
        "The Sculptors' Guild",
        "The Shipwrights' Guild",
        "The Spice Merchants' Guild",
        "The Stonemasons' Guild",
        "The Tailors' Guild",
        "The Tanners' Guild",
        "The Thieves' Guild",
        "The Torturers' Guild",
        "The Vintners' Guild",
        "The Weavers' Guild",
        "The Woodcarvers' Guild",
        "The Woodsmen's Guild",
        "The Alchemists' Guild",
        "The League of Arcane Architects",
        "The Circle of Shadow Weavers",
        "The Covenant of Eternal Flame",
        "The Assembly of Dragon Riders",
        "The Syndicate of Ravenous Wolves",
        "The Union of Elementalists",
        "The Cult of the Crimson Moon",
        "The Guild of the Silver Fang",
        "The Conclave of the Silent Council",
        "The Association of the Golden Sun",
        "The Coalition of the Black Rose",
        "The Syndicate of the Iron Fist",
        "The Alliance of the Emerald Star",
        "The Fellowship of the Mystic Moon",
        "The Guild of the Enchanted Quill",
        "The Society of the Celestial Harp",
        "The Order of the Celestial Crusaders",
        "The Brotherhood of the Cursed Blade",
        "The Council of the Mystic Mountain",
        "The Guild of the Emerald Flame",
        "The Fellowship of the Everlasting Spring",
        "The Order of the Golden Phoenix",
        "The Coral Palace",
        "The Pearl Reef",
        "The Sunken City",
        "The Leviathan's Lair",
        "The Sea Witch's Cove",
        "The Mermaid's Grotto",
        "The Kraken's Den",
        "The Maelstrom's Edge",
        "The Triton's Throne",
        "The Seabirds' Sanctuary",
        "The Siren's Lagoon",
        "The Seahorse Stables",
        "The Shark's Tooth Island",
        "The Tidal Caverns",
        "The Whirlpool Bay",
        "The Sea Dragon's Lair",
        "The Underwater Gardens",
        "The Merrow's Domain",
        "The Sunken Shipyard",
        "The Octopus's Garden",
        "The Nautilus's Nest",
        "An Underwater City",
        "Sunken Ruins",
        "A Sea Fortress",
        "A Pirate Cove",
        "A Coral Garden",
        "A Secluded Beach",
        "A Lost Island",
        "A Treacherous Reef",
        "A Mysterious Bay",
        "A Tidal Cave",
        "The Dark Abyss",
        "Crystal Waters",
        "An Ancient Harbor",
        "A Coastal Town",
        "A Rusty Wreck",
        "An Eerie Shipwreck",
        "A Murky Swamp",
        "Smuggler's Bay",
        "A Sea Cavern",
        "A Black Coral Forest",
        "A Hidden Grotto",
        "A Turquoise Lagoon",
        "A Stormy Sea",
        "A Seaweed Forest",
        "A Coastal Fortress",
        "An Abandoned Dock",
        "An Underwater Cave",
        "A local tavern",
        "The King's Market",
        "The Iron Anvil",
        "The Golden Spindle",
        "The Emerald Garden",
        "The Stag's Head Inn",
        "The Blue Moon Tavern",
        "The Holy Chapel",
        "Whispering Woods Cemetery",
        "The Watchman's Tower",
        "The Citadel",
        "The Baron's Manor",
        "The Rustic Cottage",
        "The Herb Haven",
        "The Dairy Delight",
        "The Wheatfield Wagon",
        "The Fruitful Orchard",
        "The Golden Grain Brewery",
        "The Sweet Crust Bakery",
        "The Cobbler's Corner",
        "The Tannery Tower",
        "The Silver Fishmonger",
        "The Noble Butcher",
        "The Cheese Wheel Emporium",
        "The Candlelit Cave",
        "The Oak Barrel Cooperage",
        "The Carpenter's Corner",
        "The Stone Mason's Hall",
    ],
    adjectives: [
        "Adaptable",
        "Adventurous",
        "Affectionate",
        "Agile",
        "Ambitious",
        "Amusing",
        "Analytical",
        "Angelic",
        "Animated",
        "Appreciative",
        "Approachable",
        "Articulate",
        "Assertive",
        "Attentive",
        "Authentic",
        "Beautiful",
        "Benevolent",
        "Blissful",
        "Bold",
        "Brave",
        "Bright",
        "Brilliant",
        "Calm",
        "Capable",
        "Captivating",
        "Carefree",
        "Caring",
        "Charismatic",
        "Charming",
        "Cheerful",
        "Clean",
        "Clever",
        "Colorful",
        "Comfortable",
        "Compassionate",
        "Confident",
        "Considerate",
        "Cooperative",
        "Courageous",
        "Creative",
        "Cultivated",
        "Curious",
        "Daring",
        "Dazzling",
        "Decent",
        "Dedicated",
        "Delightful",
        "Dependable",
        "Determined",
        "Devoted",
        "Disciplined",
        "Discreet",
        "Distinguished",
        "Dynamic",
        "Earnest",
        "Easygoing",
        "Educated",
        "Efficient",
        "Elegant",
        "Empathetic",
        "Energetic",
        "Enthusiastic",
        "Ethical",
        "Euphoric",
        "Exhilarated",
        "Experienced",
        "Expressive",
        "Exquisite",
        "Extravagant",
        "Fair",
        "Faithful",
        "Fancy",
        "Fantastic",
        "Fearless",
        "Fierce",
        "Flexible",
        "Flirty",
        "Focused",
        "Forceful",
        "Forgiving",
        "Fortunate",
        "Friendly",
        "Frisky",
        "Fun",
        "Funny",
        "Generous",
        "Gentle",
        "Genuine",
        "Gifted",
        "Gleeful",
        "Glorious",
        "Good",
        "Gorgeous",
        "Graceful",
        "Gracious",
        "Grand",
        "Grateful",
        "Great",
        "Happy",
        "Hardy",
        "Harmonious",
        "Helpful",
        "Heroic",
        "Honest",
        "Honorable",
        "Hopeful",
        "Humble",
        "Humorous",
        "Idealistic",
        "Imaginative",
        "Impartial",
        "Impassioned",
        "Impressive",
        "Independent",
        "Industrious",
        "Influential",
        "Informed",
        "Ingenious",
        "Innocent",
        "Inquisitive",
        "Insightful",
        "Inspired",
        "Intense",
        "Intelligent",
        "Intuitive",
        "Inventive",
        "Invigorated",
        "Joyful",
        "Jubilant",
        "Juicy",
        "Just",
        "Keen",
        "Kind",
        "Knowing",
        "Knowledgeable",
        "Laid",
        "Large-hearted",
        "Lively",
        "Logical",
        "Long-sighted",
        "Loquacious",
        "Lovable",
        "Loving",
        "Loyal",
        "Lucid",
        "Lucky",
        "Luminous",
        "Magnanimous",
        "Majestic",
        "Masterful",
        "Mature",
        "Mellow",
        "Memorable",
        "Merciful",
        "Merry",
        "Methodical",
        "Mighty",
        "Mindful",
        "Modest",
        "Motivated",
        "Mysterious",
        "Natural",
        "Neat",
        "Noble",
        "Nurturing",
        "Observant",
        "Open",
        "Open-hearted",
        "Optimistic",
        "Orderly",
        "Organized",
        "Original",
        "Outgoing",
        "Passionate",
        "Patient",
        "Peaceful",
        "Perfect",
        "Persevering",
        "Persistent",
        "Persuasive",
        "Playful",
        "Pleasant",
        "Polite",
        "Popular",
        "Positive",
        "Powerful",
        "Pragmatic",
        "Precise",
        "Prepared",
        "Present",
        "Pretty",
        "Principled",
        "Productive",
        "Proficient",
        "Progressive",
        "Punctual",
        "Pure",
        "Purposeful",
        "Quick",
        "Quick-witted",
        "Quiet",
        "Radiant",
        "Rational",
        "Ready",
        "Realistic",
        "Reasonable",
        "Receptive",
        "Refreshed",
        "Regal",
        "Reliable",
        "Resourceful",
        "Respectful",
        "Responsible",
        "Reverent",
        "Rich",
        "Robust",
        "Romantic",
        "Rustic",
        "Satisfying",
        "Satisfactory",
        "Satisfied",
        "Savvy",
        "Scintillating",
        "Secure",
        "Self-assured",
        "Self-confident",
        "Self-disciplined",
        "Self-reliant",
        "Sensational",
        "Sensitive",
        "Sensible",
        "Sensual",
        "Serene",
        "Sharp",
        "Shimmering",
        "Shrewd",
        "Simple",
        "Sincere",
        "Skillful",
        "Smart",
        "Smiling",
        "Smooth",
        "Social",
        "Sociable",
        "Solid",
        "Soothing",
        "Sophisticated",
        "Sparkling",
        "Spirited",
        "Spiritual",
        "Spontaneous",
        "Sporty",
        "Spry",
        "Stable",
        "Stalwart",
        "Standing",
        "Startling",
        "Steadfast",
        "Steady",
        "Stimulating",
        "Stoic",
        "Striking",
        "Strong",
        "Stunning",
        "Stylish",
        "Suave",
        "Sublime",
        "Successful",
        "Super",
        "Supple",
        "Supportive",
        "Sure-footed",
        "Surprising",
        "Sweeping",
        "Sweet",
        "Swift",
        "Sympathetic",
        "Systematic",
        "Tactful",
        "Tasteful",
        "Tender",
        "Terrific",
        "Thankful",
        "Thorough",
        "Thoughtful",
        "Thrifty",
        "Thrilled",
        "Thriving",
        "Timely",
        "Tireless",
        "Tough",
        "Tranquil",
        "Transformative",
        "Transparent",
        "Trusting",
        "Trustworthy",
        "Truthful",
        "Unassuming",
        "Uncommon",
        "Understanding",
        "Undeterred",
        "Undisputed",
        "Unique",
        "Unselfish",
        "Unshakeable",
        "Uplifting",
        "Urbane",
        "Valiant",
        "Valid",
        "Valuable",
        "Vibrant",
        "Vigilant",
        "Vigorous",
        "Visionary",
        "Vital",
        "Vivacious",
        "Warm",
        "Warm-hearted",
        "Watchful",
        "Wealthy",
        "Welcoming",
        "Well-behaved",
        "Well-connected",
        "Well-educated",
        "Well-informed",
        "Well-mannered",
        "Well-read",
        "Well-rounded",
        "Whimsical",
        "Wholehearted",
        "Willful",
        "Willing",
        "Wise",
        "Witty",
        "Wonderful",
        "Workaholic",
        "Worldly",
        "Youthful",
        "Zealous",
        "Abiding",
        "Able",
        "Abundant",
        "Accurate",
        "Achieving",
        "Alert",
        "Aligned",
        "Alive",
        "Alluring",
        "Ample",
        "Appealing",
        "Artistic",
        "Assiduous",
        "Astute",
        "Attractive",
        "Awesome",
        "Believe",
        "Beneficent",
        "Benign",
        "Best",
        "Better",
        "Boundless",
        "Breezy",
        "Broad-minded",
        "Buoyant",
        "Careful",
        "Celebrated",
        "Certain",
        "Challenging",
        "Chic",
        "Civil",
        "Classic",
        "Clear",
        "Clement",
        "Close",
        "Coherent",
        "Collected",
        "Commanding",
        "Commendable",
        "Compatible",
        "Complete",
        "Composed",
        "Concise",
        "Congenial",
        "Connected",
        "Conscious",
        "Consistent",
        "Constant",
        "Constructive",
        "Contemplative",
        "Convenient",
        "Cool",
        "Courteous",
        "Credible",
        "Crisp",
        "Crucial",
        "Cultured",
        "Cute",
        "Dainty",
        "Decisive",
        "Defiant",
        "Deft",
        "Delicate",
        "Delicious",
    ],
};
