//export const classes = ["Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard", "Artificer"];
export const classes = [
    "Merchant",
    "Blacksmith",
    "Bowyer",
    "Herbalist",
    "Jester",
    "Innkeeper",
    "Carpenter",
    "Lumberjack",
    "Mason",
    "Leatherworker",
    "Tailor",
    "Miller",
    "Baker",
    "Cook",
    "Jeweler",
    "Librarian",
    "Astrologer",
    "Cartographer",
    "Sailor",
    "Fisherman",
    "Farmer",
    "Beekeeper",
    "Miner",
    "Mayor",
    "Noble",
    "Historian",
    "Butcher",
    "Guild Master",
    "Priest",
    "Banker",
    "Archaeologist",
    "Crime Boss",
];
export const races = ["Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", "Half-Orc", "Halfling", "Human", "Tiefling", "Goliath"];

const pathfinderClasses = ["Alchemist", "Investigator", "Magus", "Oracle", "Psychic", "Summoner", "Swashbuckler", "Thaumaturge", "Gunslinger"];
const pathfinderRaces = ["Azarketi", "Leshy", "Fetchling", "Gnoll", "Grippli", "Kitsune", "Nagaji", "Ratfolk", "Vanara"];
const dndRaces = ["Aarakocra", "Tortle", "Aasimar", "Firbolg", "Genasi (water, fire, earth or air)", "Bugbear", "Fairy", "Satyr"];
const commonRaces = ["Goblin", "Kenku", "Kobold", "Hobgoblin", "Lizardfolk", "Orc", "Catfolk", "Warforged"];

const professions = [
    "Merchant",
    "Blacksmith",
    "Armorer",
    "Bowyer",
    "Herbalist",
    "Jester",
    "Local Wizard",
    "Innkeeper",
    "Stable Master",
    "Carpenter",
    "Lumberjack",
    "Mason",
    "Leatherworker",
    "Tailor",
    "Miller",
    "Baker",
    "Cook",
    "Jeweler",
    "Librarian",
    "Astrologer",
    "Cartographer",
    "Sailor",
    "Fisherman",
    "Farmer",
    "Beekeeper",
    "Miner",
    "Mayor",
    "Noble",
    "Historian",
    "Butcher",
    "Guild Master",
    "Priest",
    "Banker",
    "Archaeologist",
    "Crime Boss",
];
